# Generated by Django 5.0.1 on 2024-02-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='is_active',
            new_name='is_read',
        ),
    ]
