# Generated by Django 5.0.1 on 2024-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
