# Generated by Django 5.0.1 on 2024-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='current',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='limit',
            field=models.IntegerField(default=2),
        ),
    ]
